### PR TITLE
Finalize PDF

### PR DESCRIPTION
**Pull request by Silex**
Hello,

This is what is needed for restbase to work with PDF.

Test it a little bit first to confirm.

### CODE REVIEW

**Comment by Silex** [comment]
If https://github.com/wikimedia/restbase/pull/915 gets merged we'll be able to simplify a bit.

**Comment by Silex** [comment]
@pastakhov: you need to merge this too for PDF exports to work :wink:

**EDIT**: actually wait, looks like my issue was merged I'll test wether I can simplify the config.

**Comment by Silex** [comment]
Okay, the change is in master but since we build the `0.16.9` tag my commit is not picked up.

We could cherry-pick the commit and apply it as part of the building process, but that feels a bit far-fetched just to avoid the `sed` line.

So, you can merge this IMHO.

**Review by pastakhov — APPROVED** [review]

**Comment by UFOMelkor** [comment]
Did I miss something or is this not yet released?

**Comment by Silex** [comment]
@UFOMelkor: I think you are correct. @pastakhov seems to have gone away a little :-)

**Pull request merged**
